controllers/CarController.php
<?php

namespace app\controllers;

use yii;
use app\components\CommonController;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use app\models\Transfers;
use app\models\Voucher;
use app\models\Flights;
use app\models\Activity;
use app\models\Car;
use yii\helpers\BaseFileHelper;
use yii\web\UploadedFile;
use yii\helpers\Url;

/**
 * Default controller for the `admin` module
 */
class CarController extends CommonController {

    /**
     * opens the List of all the not deleted Cars in the system
     * @return string
     */
    public function actionIndex() {
        $model = Car::find()->where(['<>', 'status', '2'])->orderBy(['id' => SORT_DESC])->all();
        return $this->render('index', ['model' => $model]);
    }

    public function actionCreate() {
        $car = new Car();
        if (Yii::$app->request->isPost) {
            $car->attributes = $_POST['Car'];
            $car->created_at = date('Y-m-d H:i:s');
            $car->status = '1';
            if ($car->validate()) {
                if ($car->save()) {
                    Yii::$app->session->setFlash('carSubmitted', 'The Car has been saved.');

                    return $this->redirect(['index']);
                }
            }
        }
        return $this->render('create', ['model' => $car]);
    }

    public function actionDelete($id) {
        $model = Car::find()
                ->where(['id' => $id])
                ->one();
        $model->status = '2';
        $model->update(false);

        return $this->redirect(['index']);
    }

    public function actionEdit($id) {
        $data = Car::find()
                ->where(['id' => $id])
                ->one();
        $data->update();
        $data->updated_at = date('Y-m-d H:i:s');
        if ($data->load(Yii::$app->request->post()) && $data->save() && $data->validate()) {
            if ($data->save()) {
                Yii::$app->getSession()->setFlash('message', 'Car updated sucessfully');
                return $this->redirect(['index']);
            }
        }
        return $this->render('update', ['model' => $data,]);
    }

}

controllers/ReportController.php
<?php

namespace app\controllers;

use Yii;
use app\components\CommonController;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use app\models\LoginForm;
use app\models\Transfers;
use \app\models\Activity;
use app\models\Flights;
use kartik\mpdf\Pdf;

class ReportController extends CommonController {

    /**
     * Index action.
     *
     * @return string
     */
    public function actionIndex() {
        return $this->render('index');
    }

    /**
     * opens the daily transfer Report
     * @return type
     */
    public function actionDailyTransferReport() {
        $upper = date('Y-m-d');
        $lower = date('Y-m-d');
        $city_name = 'BANGKOK';
        $city_key = 'BKK';
        if (Yii::$app->request->isPost) {
            $lower = isset($_POST['order-start-date']) && !empty($_POST['order-start-date']) ? date('Y-m-d', strtotime(explode(' - ', $_POST['order-start-date'])[0])) : '0000-00-00';
            $upper = isset($_POST['order-start-date']) && !empty($_POST['order-start-date']) ? date('Y-m-d', strtotime(explode(' - ', $_POST['order-start-date'])[1])) : '2090-12-31';
            $lower1 = isset($_POST['tour-start-date']) && !empty($_POST['tour-start-date']) ? date('Y-m-d', strtotime(explode(' - ', $_POST['tour-start-date'])[0])) : '0000-00-00';
            $upper1 = isset($_POST['tour-start-date']) && !empty($_POST['tour-start-date']) ? date('Y-m-d', strtotime(explode(' - ', $_POST['tour-start-date'])[1])) : '2090-12-31';
            $city = isset($_POST['city']) && !empty($_POST['city']) ? Yii::$app->request->post('city') : '';
            if ($city == 2) {
                $model = Transfers::find()->where(['<>', 'status', '2'])->andWhere(['and', "DATE(transfer_date)>='$lower1'", "DATE(transfer_date)<='$upper1'"])->andWhere(['and', "DATE(created_at)>='$lower'", "DATE(created_at)<='$upper'"])->andWhere(['or', "UPPER(transfer_source) LIKE '%PT%' OR UPPER(transfer_source) LIKE '%Pattaya%'", "UPPER(transfer_destination) LIKE '%BKK%' OR UPPER(transfer_destination) LIKE '%Bangkok%'"])->orderBy(['id' => SORT_DESC])->all();
            } else if ($city == 3) {
                $model = Transfers::find()->where(['<>', 'status', '2'])->andWhere(['and', "DATE(transfer_date)>='$lower1'", "DATE(transfer_date)<='$upper1'"])->andWhere(['and', "DATE(created_at)>='$lower'", "DATE(created_at)<='$upper'"])->andWhere(['or', "UPPER(transfer_source) LIKE '%HKT%' OR UPPER(transfer_source) LIKE '%PHUKET%'", "UPPER(transfer_destination) LIKE '%KBV%' OR UPPER(transfer_destination) LIKE '%KRABI%'"])->orderBy(['id' => SORT_DESC])->all();
            } else if ($city == 4) {
                $model = Transfers::find()->where(['<>', 'status', '2'])->andWhere(['and', "DATE(transfer_date)>='$lower1'", "DATE(transfer_date)<='$upper1'"])->andWhere(['and', "DATE(created_at)>='$lower'", "DATE(created_at)<='$upper'"])->andWhere(['or', "UPPER(transfer_source) LIKE '%KBV%' OR UPPER(transfer_source) LIKE '%KRABI%'", "UPPER(transfer_destination) LIKE '%HKT%' OR UPPER(transfer_destination) LIKE '%PHUKET%'"])->orderBy(['id' => SORT_DESC])->all();
            } else if ($city == 5) {
                $model = Transfers::find()->where(['<>', 'status', '2'])->andWhere(['and', "DATE(transfer_date)>='$lower1'", "DATE(transfer_date)<='$upper1'"])->andWhere(['and', "DATE(created_at)>='$lower'", "DATE(created_at)<='$upper'"])->andWhere(['or', "UPPER(transfer_source) LIKE '%BKK%' OR UPPER(transfer_source) LIKE '%Bangkok%' OR UPPER(transfer_destination) LIKE '%BKK%' OR UPPER(transfer_destination) LIKE '%Bangkok%'", "UPPER(transfer_source) LIKE '%PT%' OR UPPER(transfer_source) LIKE '%Pattaya%' OR UPPER(transfer_destination) LIKE '%PT%' OR UPPER(transfer_destination) LIKE '%Pattaya%'"])->orderBy(['id' => SORT_DESC])->all();
            } else if ($city == 6) {
                $model = Transfers::find()->where(['<>', 'status', '2'])->andWhere(['and', "DATE(transfer_date)>='$lower1'", "DATE(transfer_date)<='$upper1'"])->andWhere(['and', "DATE(created_at)>='$lower'", "DATE(created_at)<='$upper'"])->andWhere(['or', "UPPER(transfer_source) LIKE '%KBV%' OR UPPER(transfer_source) LIKE '%KRABI%' OR UPPER(transfer_destination) LIKE '%KBV%' OR UPPER(transfer_destination) LIKE '%KRABI%'", "UPPER(transfer_source) LIKE '%HKT%' OR UPPER(transfer_source) LIKE '%PHUKET%' OR UPPER(transfer_destination) LIKE '%HKT%' OR UPPER(transfer_destination) LIKE '%PHUKET%'"])->orderBy(['id' => SORT_DESC])->all();
            } else {
                $model = Transfers::find()->where(['<>', 'status', '2'])->andWhere(['and', "DATE(transfer_date)>='$lower1'", "DATE(transfer_date)<='$upper1'"])->andWhere(['and', "DATE(created_at)>='$lower'", "DATE(created_at)<='$upper'"])->orderBy(['id' => SORT_DESC])->all();
            }
            return $this->render('daily_transfer_report', ['model' => $model]);
        }
        $model = Transfers::find()->where(['<>', 'status', '2'])->andWhere(['and', "DATE(transfer_date)>='$lower'", "DATE(transfer_date)<='$upper'"])->orderBy(['id' => SORT_DESC])->all();

        return $this->render('daily_transfer_report', ['model' => $model]);
    }

    /**
     * opens the daily tour Report
     * @return type
     */
    public function actionDailyTourReport() {
        $upper = date('Y-m-d');
        $lower = date('Y-m-d');
        if (Yii::$app->request->isPost) {
            $lower = isset($_POST['order-start-date']) && !empty($_POST['order-start-date']) ? date('Y-m-d', strtotime(explode(' - ', $_POST['order-start-date'])[0])) : '0000-00-00';
            $upper = isset($_POST['order-start-date']) && !empty($_POST['order-start-date']) ? date('Y-m-d', strtotime(explode(' - ', $_POST['order-start-date'])[1])) : '2090-12-31';
            $lower1 = isset($_POST['tour-start-date']) && !empty($_POST['tour-start-date']) ? date('Y-m-d', strtotime(explode(' - ', $_POST['tour-start-date'])[0])) : '0000-00-00';
            $upper1 = isset($_POST['tour-start-date']) && !empty($_POST['tour-start-date']) ? date('Y-m-d', strtotime(explode(' - ', $_POST['tour-start-date'])[1])) : '2090-12-31';
            $city = isset($_POST['city']) && !empty($_POST['city']) ? Yii::$app->request->post('city') : '';
            $model = Activity::find()->where(['<>', 'status', '2'])->andWhere(['and', "tour_date>=DATE('$lower1')", "tour_date<=DATE('$upper1')"])->andWhere(['and', "DATE(created_at)>='$lower'", "DATE(created_at)<='$upper'"])->orderBy(['tour_date' => SORT_DESC, 'UPPER(tour_name)' => SORT_DESC])->andWhere(['LIKE', 'destination', $city])->all();
            return $this->render('daily_tour_report', ['model' => $model]);
        }
        $model = Activity::find()->where(['<>', 'status', '2'])->andWhere(['and', "tour_date>='$lower'", "tour_date<='$upper'"])->orderBy(['id' => SORT_DESC])->all();

        return $this->render('daily_tour_report', ['model' => $model]);
    }

    /**
     * lets you force download a pdf file for the transfers filtered by date
     * @return type
     */
    function actionDownloadTransferPdf() {

        $upper = date('Y-m-d');
        $lower = date('Y-m-d');
        if (Yii::$app->request->isPost) {

            $lower = isset($_POST['order-start-date']) && !empty($_POST['order-start-date']) ? date('Y-m-d', strtotime(explode(' - ', $_POST['order-start-date'])[0])) : '0000-00-00';
            $upper = isset($_POST['order-start-date']) && !empty($_POST['order-start-date']) ? date('Y-m-d', strtotime(explode(' - ', $_POST['order-start-date'])[1])) : '2090-12-31';
            $lower1 = isset($_POST['tour-start-date']) && !empty($_POST['tour-start-date']) ? date('Y-m-d', strtotime(explode(' - ', $_POST['tour-start-date'])[0])) : '0000-00-00';
            $upper1 = isset($_POST['tour-start-date']) && !empty($_POST['tour-start-date']) ? date('Y-m-d', strtotime(explode(' - ', $_POST['tour-start-date'])[1])) : '2090-12-31';


            if (isset($_POST['order-start-date']) && !empty($_POST['order-start-date'])) {
                $date = date('l jS \of F Y', strtotime(explode(' - ', $_POST['order-start-date'])[0]));
                $date .= ' to ' . date('l jS \of F Y', strtotime(explode(' - ', $_POST['order-start-date'])[1]));
            } else if (isset($_POST['tour-start-date']) && !empty($_POST['tour-start-date'])) {
                $date = date('l jS \of F Y', strtotime(explode(' - ', $_POST['tour-start-date'])[0]));
                $date .= ' to ' . date('l jS \of F Y', strtotime(explode(' - ', $_POST['tour-start-date'])[1]));
            } else {
                $date = date('l jS \of F Y', strtotime(explode(' - ', $lower)));
                $date = date('l jS \of F Y', strtotime(explode(' - ', $upper)));
            }
            $model = Transfers::find()->where(['<>', 'status', '2'])->andWhere(['and', "DATE(transfer_date)>='$lower1'", "DATE(transfer_date)<='$upper1'"])->andWhere(['and', "DATE(created_at)>='$lower'", "DATE(created_at)<='$upper'"])->orderBy(['id' => SORT_DESC])->all();
        } else {
            return $this->redirect(['daily-transfer-report']);
        }
        $this->layout = 'template';
//        return $this->render('../templates/mpdf_transfer_report');
        $content = $this->renderPartial('../templates/mpdf_transfer_report', ['model' => $model, 'date' => $date]);
        $pdf = new Pdf([
            'mode' => Pdf::MODE_UTF8,
            'filename' => 'Transfer Report.pdf',
            'format' => Pdf::FORMAT_A4,
            'orientation' => Pdf::ORIENT_PORTRAIT,
            'destination' => Pdf::DEST_DOWNLOAD,
            'content' => $content,
            'cssFile' => '@vendor/kartik-v/yii2-mpdf/assets/kv-mpdf-bootstrap.min.css',
            'cssInline' => '.img-container img {width: 100%;overflow: hidden;}',
            'options' => ['title' => 'Transfer Report'],
            'methods' => [
                'SetHeader' => ['Erawan'],
                'SetFooter' => ['{PAGENO}'],
            ]
        ]);
        $pdf->render();
    }

    /**

views/layouts/_footer.php
<div class="page-footer">
    <div class="page-footer-inner"> 2018 &copy; Admin Theme Metronics
    </div>
    <div class="scroll-to-top">
        <i class="icon-arrow-up"></i>
    </div>
</div>

views/layouts/_header.php
<style>
    
    
    a.logo img {
        width: 80%;
        display: block;
        
    }
    
</style>
<header class="header fixed-top clearfix">
    <!--logo start-->
    <div class="brand">

        <a href="<?= Yii::$app->request->baseUrl; ?>/auth/index" class="logo">
            <img src="<?= Yii::$app->request->baseUrl; ?>/assets/admin/images/logo.png" alt="">
        </a>
        <div class="sidebar-toggle-box">
            <div class="fa fa-bars"></div>
        </div>
    </div>
    <!--logo end-->

    <div class="nav notify-row" id="top_menu">
        <!--  notification start -->
<!--        <ul class="nav top-menu">
             settings start 
            <li class="dropdown">
                <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                    <i class="fa fa-tasks"></i>
                    <span class="badge bg-success">8</span>
                </a>
                <ul class="dropdown-menu extended tasks-bar">
                    <li>
                        <p class="">You have 8 pending tasks</p>
                    </li>
                    <li>
                        <a href="#">
                            <div class="task-info clearfix">
                                <div class="desc pull-left">
                                    <h5>Target Sell</h5>
                                    <p>25% , Deadline  12 June’13</p>
                                </div>
                                <span class="notification-pie-chart pull-right" data-percent="45">
                                    <span class="percent"></span>
                                </span>
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <div class="task-info clearfix">
                                <div class="desc pull-left">
                                    <h5>Product Delivery</h5>
                                    <p>45% , Deadline  12 June’13</p>
                                </div>
                                <span class="notification-pie-chart pull-right" data-percent="78">
                                    <span class="percent"></span>
                                </span>
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <div class="task-info clearfix">
                                <div class="desc pull-left">
                                    <h5>Payment collection</h5>
                                    <p>87% , Deadline  12 June’13</p>
                                </div>
                                <span class="notification-pie-chart pull-right" data-percent="60">
                                    <span class="percent"></span>
                                </span>
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <div class="task-info clearfix">
                                <div class="desc pull-left">
                                    <h5>Target Sell</h5>
                                    <p>33% , Deadline  12 June’13</p>
                                </div>
                                <span class="notification-pie-chart pull-right" data-percent="90">
                                    <span class="percent"></span>
                                </span>
                            </div>
                        </a>
                    </li>

                    <li class="external">
                        <a href="#">See All Tasks</a>
                    </li>
                </ul>
            </li>
             settings end 
             inbox dropdown start
            <li id="header_inbox_bar" class="dropdown">
                <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                    <i class="fa fa-envelope-o"></i>
                    <span class="badge bg-important">4</span>
                </a>
                <ul class="dropdown-menu extended inbox">
                    <li>
                        <p class="red">You have 4 Mails</p>
                    </li>
                    <li>
                        <a href="#">
                            <span class="photo"><img alt="avatar" src="<?= Yii::$app->request->baseUrl; ?>/assets/admin/images/avatar-mini.jpg"></span>
                            <span class="subject">
                                <span class="from">Jonathan Smith</span>
                                <span class="time">Just now</span>
                            </span>
                            <span class="message">
                                Hello, this is an example msg.
                            </span>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <span class="photo"><img alt="avatar" src="<?= Yii::$app->request->baseUrl; ?>/assets/admin/images/avatar-mini-2.jpg"></span>
                            <span class="subject">
                                <span class="from">Jane Doe</span>
                                <span class="time">2 min ago</span>
                            </span>
                            <span class="message">
                                Nice admin template
                            </span>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <span class="photo"><img alt="avatar" src="<?= Yii::$app->request->baseUrl; ?>/assets/admin/images/avatar-mini-3.jpg"></span>
                            <span class="subject">
                                <span class="from">Tasi sam</span>
                                <span class="time">2 days ago</span>
                            </span>
                            <span class="message">
                                This is an example msg.
                            </span>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <span class="photo"><img alt="avatar" src="<?= Yii::$app->request->baseUrl; ?>/assets/admin/images/avatar-mini.jpg"></span>
                            <span class="subject">
                                <span class="from">Mr. Perfect</span>
                                <span class="time">2 hour ago</span>
                            </span>
                            <span class="message">
                                Hi there, its a test
                            </span>
                        </a>
                    </li>
                    <li>
                        <a href="#">See all messages</a>
                    </li>
                </ul>
            </li>
             inbox dropdown end 
             notification dropdown start
            <li id="header_notification_bar" class="dropdown">
                <a data-toggle="dropdown" class="dropdown-toggle" href="#">

                    <i class="fa fa-bell-o"></i>
                    <span class="badge bg-warning">3</span>
                </a>
                <ul class="dropdown-menu extended notification">
                    <li>
                        <p>Notifications</p>
                    </li>
                    <li>
                        <div class="alert alert-info clearfix">
                            <span class="alert-icon"><i class="fa fa-bolt"></i></span>
                            <div class="noti-info">
                                <a href="#"> Server #1 overloaded.</a>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="alert alert-danger clearfix">
                            <span class="alert-icon"><i class="fa fa-bolt"></i></span>
                            <div class="noti-info">
                                <a href="#"> Server #2 overloaded.</a>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="alert alert-success clearfix">
                            <span class="alert-icon"><i class="fa fa-bolt"></i></span>
                            <div class="noti-info">
                                <a href="#"> Server #3 overloaded.</a>
                            </div>
                        </div>
                    </li>

                </ul>
            </li>
             notification dropdown end 
        </ul>-->
        <!--  notification end -->
    </div>
    <div class="top-nav clearfix">
        <!--search & user info start-->
        <ul class="nav pull-right top-menu">
            <li>
                <input type="text" class="form-control search" placeholder=" Search">
            </li>
            <!-- user login dropdown start-->
            <li class="dropdown">
                <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                    <img alt="" src="<?= Yii::$app->request->baseUrl; ?>/assets/admin/images/avatar1_small.jpg">
                    <span class="username"><?= Yii::$app->user->identity->email; ?></span>
                    <b class="caret"></b>
                </a>
                <ul class="dropdown-menu extended logout">
                    <li><a href="#"><i class=" fa fa-suitcase"></i>Profile</a></li>
                    <!--<li><a href="#"><i class="fa fa-cog"></i> Settings</a></li>-->
                    <li><a href="<?= Yii::$app->request->baseUrl; ?>/auth/logout"><i class="fa fa-key"></i> Log Out</a></li>
                </ul>
            </li>
            <!-- user login dropdown end -->
            <li>
<!--                <div class="toggle-right-box">
                    <div class="fa fa-bars"></div>
                </div>-->
            </li>
        </ul>
        <!--search & user info end-->
    </div>
</header>

views/layouts/_sidebar_left.php
<aside>
    <div id="sidebar" class="nav-collapse">
        <!-- sidebar menu start-->
        <div class="leftside-navigation">
            <ul class="sidebar-menu" id="nav-accordion">
                <li>
                    <a class="<?= Yii::$app->controller->id == 'dashboard' ? 'active' : ''; ?>" href="<?= Yii::$app->request->baseUrl . '/dashboard/index'; ?>">
                        <i class="fa fa-dashboard"></i>
                        <span>Dashboard</span>
                    </a>
                </li>
                <li class="sub-menu">
                    <a href="javascript:;" class="<?= Yii::$app->controller->id == 'voucher' ? 'active' : ''; ?>">
                        <i class="fa fa-laptop"></i>
                        <span>Vouchers</span>
                    </a>
                    <ul class="sub">
                        <li class="<?= Yii::$app->controller->id == 'voucher' && Yii::$app->controller->action->id == 'index' ? 'active' : ''; ?>"><a href="<?= Yii::$app->request->baseUrl . '/voucher/index'; ?>">Booking</a></li>
                        <li class="<?= Yii::$app->controller->id == 'voucher' && Yii::$app->controller->action->id == 'excelupload' ? 'active' : ''; ?>"><a href="<?= Yii::$app->request->baseUrl . '/voucher/excelupload'; ?>">Upload EXCEL</a></li>
                        <li class="<?= Yii::$app->controller->id == 'voucher' && Yii::$app->controller->action->id == 'add-voucher' ? 'active' : ''; ?>"><a href="<?= Yii::$app->request->baseUrl . '/voucher/add-voucher'; ?>">Add Voucher</a></li>
                    </ul>
                </li>
                <li>
                    <a class="<?= Yii::$app->controller->id == 'invoice' ? 'active' : ''; ?>" href="<?= Yii::$app->request->baseUrl . '/dashboard/index'; ?>">
                        <i class="fa fa-dashboard"></i>
                        <span>Invoice</span>
                    </a>
                    <ul class="sub">
                        <li class="<?= Yii::$app->controller->id == 'invoice' && Yii::$app->controller->action->id == 'incoming-invoice-index' ? 'active' : ''; ?>"><a href="<?= Yii::$app->request->baseUrl . '/invoice/incoming-invoice-index'; ?>">Incoming Invoices</a></li>
                        <li class="<?= Yii::$app->controller->id == 'invoice' && Yii::$app->controller->action->id == 'outgoing-invoice-view' ? 'active' : ''; ?>"><a href="<?= Yii::$app->request->baseUrl . '/invoice/outgoing-invoice-view'; ?>">Outgoing Invoices</a></li>
                    </ul>
                </li>
                <li class="sub-menu">
                    <a href="javascript:;" class="<?= Yii::$app->controller->id == 'report' ? 'active' : ''; ?>">
                        <i class="fa fa-laptop"></i>
                        <span>Reports</span>
                    </a>
                    <ul class="sub">
                        <li class="<?= Yii::$app->controller->id == 'report' && Yii::$app->controller->action->id == 'daily-transfer-report' ? 'active' : ''; ?>"><a href="<?= Yii::$app->request->baseUrl . '/report/daily-transfer-report'; ?>">Daily Transfers</a></li>
                        <li class="<?= Yii::$app->controller->id == 'report' && Yii::$app->controller->action->id == 'daily-tour-report' ? 'active' : ''; ?>"><a href="<?= Yii::$app->request->baseUrl . '/report/daily-tour-report'; ?>">Daily Tours</a></li>
                        <li><a href="language_switch.html">Booking</a></li>
                        <li><a href="language_switch.html">Supplier</a></li>
                    </ul>
                </li>
                 <li>
                    <a class="<?= Yii::$app->controller->id == 'supplier' ? 'active' : ''; ?>" href="<?= Yii::$app->request->baseUrl . '/supplier/index'; ?>" >
                        <i class="fa fa-user"></i>
                        <span>Supplier</span>
                    </a>
                      
                </li>

                <li>
                    <a class="<?= Yii::$app->controller->id == 'car' ? 'active' : ''; ?>" href="<?= Yii::$app->request->baseUrl . '/car/index'; ?>">
                        <i class="fa fa-dashboard"></i>
                        <span>Available Cars</span>
                    </a>
                </li>
                <li>
                    <a class="<?= Yii::$app->controller->id == 'agent' ? 'active' : ''; ?>" href="<?= Yii::$app->request->baseUrl . '/dashboard/index'; ?>">
                        <i class="fa fa-dashboard"></i>
                        <span>Agents</span>
                    </a>
                </li>
                 <li>
                    <a class="<?= Yii::$app->controller->id == 'settings' ? 'active' : ''; ?>" href="<?= Yii::$app->request->baseUrl . '/dashboard/index'; ?>">
                        <i class="fa fa-dashboard"></i>
                        <span>Site Settings</span>
                    </a>
                    <ul class="sub">
                        <li class="<?= Yii::$app->controller->id == 'settings' && Yii::$app->controller->action->id == 'sight' ? 'active' : ''; ?>"><a href="<?= Yii::$app->request->baseUrl . '/settings/index'; ?>"> Currency</a></li>
                       
                    </ul>
                </li>
            </ul>         
        </div>
        <!-- sidebar menu end-->
    </div>
</aside>

views/layouts/error.php
<?php

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
?>
<?php $this->beginPage() ?>

<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>">
        <?= Html::csrfMetaTags() ?>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="WebIdeaSole">

        <meta http-equiv=”X-UA-Compatible” content=”IE=EmulateIE9”>
        <meta http-equiv=”X-UA-Compatible” content=”IE=9”>
        <?php $this->head() ?>
        <?php $this->registerLinkTag(['href' => Yii::$app->request->baseUrl . 'web/assets/admin/images/favicon.png']); ?>
        <title><?= Html::encode($this->title) ?></title>

        <!--Core CSS -->
        <?php $this->registerCssFile("@web/assets/admin/bs3/css/bootstrap.min.css"); ?>
        <?php $this->registerCssFile("@web/assets/admin/css/bootstrap-reset.css"); ?>
        <?php $this->registerCssFile("@web/assets/admin/font-awesome/css/font-awesome.css"); ?>
        <!--clock css-->
        <?php // $this->registerCssFile("@web/assets/admin/js/css3clock/css/style.css"); ?>
        <!--Morris Chart CSS -->
        <?php // $this->registerCssFile("@web/assets/admin/js/morris-chart/morris.css"); ?>
        <!-- Custom styles for this template -->
        <?php $this->registerCssFile("@web/assets/admin/css/style.css"); ?>
        <?php $this->registerCssFile("@web/assets/admin/css/style-responsive.css"); ?>
        <!-- Just for debugging purposes. Don't actually copy this line! -->
        <!--[if lt IE 9]>
        <script src="js/ie8-responsive-file-warning.js"></script><![endif]-->
        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
    </head>
    <body class="body-500">
        <?php $this->beginBody() ?>
        <div class="error-head"> </div>
        <div class="container ">
            <section class="error-wrapper text-center">
                <div class="error-desk">
                    <?= $content; ?>
                </div>
            </section>
            <?php $this->endBody() ?>
        </div>
    </div>
    </body>
</html>
<?php $this->endPage() ?>

views/layouts/template.php
 <?= $content; ?>