models/InvoiceIncoming.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "invoice_incoming".
 *
 * @property string $id
 * @property string $supplieir_id
 * @property string $issue_date
 * @property string $due_date
 * @property string $upload_invoice
 * @property string $payment_status
 * @property string $currency
 * @property string $created_at
 * @property string $updated_at
 * @property string $status
 */
class InvoiceIncoming extends \yii\db\ActiveRecord {

    /**
     * {@inheritdoc}
     */
    public $file;

    public static function tableName() {
        return 'invoice_incoming';
    }

    /**
     * {@inheritdoc}
     */
    public function rules() {
        return [
            [['issue_date', 'due_date', 'created_at'], 'safe'],
            [['upload_invoice', 'payment_status', 'currency', 'status'], 'string'],
            [['issue_date', 'due_date', 'payment_status', 'currency', 'status'], 'required'],
            [['supplieir_id'], 'string', 'max' => 20],
            [['file'], 'file', 'extensions' => 'pdf'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels() {
        return [
            'id' => 'ID',
            'supplieir_id' => 'Supplier ID',
            'issue_date' => 'Issue Date',
            'due_date' => 'Due Date',
            'upload_invoice' => 'Upload Invoice',
            'payment_status' => 'Payment Status',
            'currency' => 'Currency',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'status' => 'Status',
            'file' => 'Upload invoice collected from the supplier. (PDF format Only)'
        ];
    }

    public function getInvoiceParticulars() {
        return $this->hasMany(IncomingInvoiceParticulars::className(), ['incoming_invoice_id' => 'id']);
    }

    public function getSupplier() {
        return $this->hasOne(Supplier::className(), ['supplier_id' => 'supplieir_id']);
    }

    public function getInvoiceTotalAmount() {
        $amount = 0;
        if (!empty($this->invoiceParticulars)) {
            foreach ($this->invoiceParticulars as $index => $value) {
                $amount += $value->amount;
            }
        }
        return $amount;
    }

    public function oneParticular($id) {
        $model = IncomingInvoiceParticulars::find()->where(['id' => $id])->one();
        return $model ?? NULL;
    }

}

controllers/InvoiceController.php
<?php

namespace app\controllers;

use app\models\InvoiceIncoming;
use app\models\InvoiceOutgoing;
use app\components\CommonController;
use yii\helpers\ArrayHelper;
use app\models\Transfers;
use app\models\Voucher;
use app\models\Flights;
use app\models\IncomingInvoiceParticulars;
use app\models\SupplierTourName;
use app\models\Activity;
use yii\helpers\BaseFileHelper;
use yii\web\UploadedFile;
use yii\helpers\Url;
use yii;

class InvoiceController extends \app\components\CommonController {

    /**
     * create incoming invoice from admin pannel for each invoice admin gets.
     * @return type
     */
    public function actionIncomingInvoiceCreate() {


        $invoice = new InvoiceIncoming();
        $invoice_particulars = new IncomingInvoiceParticulars();
        if (Yii::$app->request->isPost) {

            $invoice->attributes = $_POST['InvoiceIncoming'];
            $invoice->created_at = date('Y-m-d H:i:s');

            $invoice->due_date = date('Y-m-d', strtotime($_POST['InvoiceIncoming']['due_date']));
            $invoice->issue_date = date('Y-m-d', strtotime($_POST['InvoiceIncoming']['issue_date']));
            $invoice->status = '1';
            $invoice->file = UploadedFile::getInstance($invoice, 'file');

            if ($invoice->file) {
                $invoice->file->saveAs('uploads/invoice/incoming/' . $invoice->file->baseName . '.' . $invoice->file->extension);
                $invoice->upload_invoice = $invoice->file->baseName . '.' . $invoice->file->extension;
                $invoice->file = null;
            }
            if ($invoice->save()) {
                foreach ($_POST['IncomingInvoiceParticulars'] as $valueInvoiceParticulars) {
                    $invoiceParticulars = new IncomingInvoiceParticulars();
                    $invoiceParticulars->attributes = $valueInvoiceParticulars;
                    $invoiceParticulars->incoming_invoice_id = $invoice->id;
                    $invoiceParticulars->service_date = date('Y-m-d', strtotime(str_replace('/','-',$valueInvoiceParticulars['service_date'])));
                    $invoiceParticulars->created_at = date('Y-m-d H:i:s');
                    $invoiceParticulars->status = '1';
                    $invoiceParticulars->save();
                    // echo '<pre>';
                    // print_r(date('Y-m-d', strtotime(str_replace('/','-',$valueInvoiceParticulars['service_date'])))); exit();
                }
                Yii::$app->session->setFlash('InvoiceSubmitted', 'The Invoice saved Successfully.');

                return $this->redirect(['incoming-invoice-index']);
            }
        }
        $tourname = SupplierTourName::find()->all();
        $model_tour_name = ArrayHelper::map($tourname, 'id', 'tourname');
        return $this->render('create_incoming', ['model' => $invoice, 'invoice_particulars' => $invoice_particulars, 'model_tour_name' => $model_tour_name]);
    }

    /**
     * view a table of all  incoming index.
     * @return type
     */
    public function actionIncomingInvoiceIndex() {
        $model = new InvoiceIncoming();

        $data = InvoiceIncoming::find()
                ->where(['<>', 'status', '2'])
                ->orderBy('id')
                ->all();

        return $this->render('index_incoming', [
                    'model' => $data,]);
    }

    /**
     * view details of a incoming invoice
     * @param type $id
     * @return type
     */
    public function actionIncomingInvoiceView($id) {
        $model = InvoiceIncoming::find()
                ->where(['id' => $id])
                ->one();
        return $this->render('view_incoming', ['model' => $model]);
    }

    public function actionIncomingInvoiceEdit($id) {
        $data = InvoiceIncoming::find()
                ->where(['id' => $id])
                ->one();

        if (Yii::$app->request->isPost) {

            $data->issue_date = isset($_POST['InvoiceIncoming']['issue_date']) && !empty($_POST['InvoiceIncoming']['issue_date']) ? date('Y-m-d', strtotime($_POST['InvoiceIncoming']['issue_date'])) : $data->issue_date;
            $data->due_date = isset($_POST['InvoiceIncoming']['due_date']) && !empty($_POST['InvoiceIncoming']['due_date']) ? date('Y-m-d', strtotime($_POST['InvoiceIncoming']['due_date'])) : $data->due_date;


            $data->updated_at = date('Y-m-d H:i:s');
            $data->file = UploadedFile::getInstance($data, 'file');

            if ($data->load(Yii::$app->request->post()) && $data->save() && $data->file && $data->validate()) {
                $data->file->saveAs('uploads/invoice/incoming/' . $data->file->baseName . '.' . $data->file->extension);
                $data->upload_invoice = $data->file->baseName . '.' . $data->file->extension;
                $data->file = null;
            }
            if ($data->save()) {

                foreach ($data->invoiceParticulars as $index => $value) {
                    $value->delete();
                }

                foreach ($_POST['IncomingInvoiceParticulars'] as $valueInvoiceParticulars) {

                    $invoiceParticulars = new IncomingInvoiceParticulars();
                    $invoiceParticulars->incoming_invoice_id = $data->id;
                    $invoiceParticulars->created_at = date('Y-m-d H:i:s');
                    $invoiceParticulars->status = '1';
                    if (isset($valueInvoiceParticulars['id']) && !empty($valueInvoiceParticulars['id']) && $data->oneParticular($valueInvoiceParticulars['id']) !== NULL) {
                        $invoiceParticulars->attributes = $data->oneParticular($valueInvoiceParticulars['id']);
                    }
                    $invoiceParticulars->attributes = $valueInvoiceParticulars;
                    $invoiceParticulars->service_date = date('Y-m-d', strtotime(str_replace('/','-',$valueInvoiceParticulars['service_date'])));
                    $invoiceParticulars->updated_at = date('Y-m-d H:i:s');
                    if ($invoiceParticulars->save()) {
                        
                    }
                    if (isset($valueInvoiceParticulars['id']) && !empty($valueInvoiceParticulars['id']) && $data->oneParticular($valueInvoiceParticulars['id']) !== NULL) {
                        $data->oneParticular($valueInvoiceParticulars['id'])->delete();
                    }
                }

                Yii::$app->getSession()->setFlash('message', 'updated sucessfully');
                return $this->redirect(['incoming-invoice-index']);
            }
        }
        $tourname = SupplierTourName::find()->all();
        $model_tour_name = ArrayHelper::map($tourname, 'id', 'tourname');
        return $this->render('update_incoming', ['model' => $data, 'model_tour_name' => $model_tour_name]);




    }

    /**
     * 
     * @return type
     */
    public function actionOutgoingInvoiceCreate() {
        $invoice = new InvoiceOutgoing();
        if (Yii::$app->request->isPost) {
            $invoice->attributes = $_POST['InvoiceOutgoing'];
            $invoice->created_at = date('Y-m-d H:i:s');
            $invoice->tourdate = date('Y-m-d', strtotime($_POST['InvoiceOutgoing']['tourdate']));

            $invoice->due_date = date('Y-m-d', strtotime($_POST['InvoiceOutgoing']['due_date']));
            $invoice->issue_date = date('Y-m-d', strtotime($_POST['InvoiceOutgoing']['issue_date']));
            $invoice->status = '1';
            $invoice->file = UploadedFile::getInstance($invoice, 'file');
            if ($invoice->file && $invoice->validate()) {
                $invoice->file->saveAs('uploads/invoice/outgoing/' . $invoice->file->baseName . '.' . $invoice->file->extension);
                $invoice->upload_invoice = $invoice->file->baseName . '.' . $invoice->file->extension;
                $invoice->file = null;
                if ($invoice->save()) {
                    Yii::$app->session->setFlash('outgoingSubmitted', 'The Invoice saved Successfully.');
                    return $this->redirect(['outgoing-invoice-view']);
                }
            }
        }
        return $this->render('outgoingcreate', ['model' => $invoice]);
    }

    /**
     * 
     * @return type
     */

    /**
     * 
     * @return type
     * 
     */
    public function actionOutgoingInvoiceView() {
        $model = new InvoiceOutgoing();

        $data = InvoiceOutgoing::find()
                ->where(['<>', 'status', '2'])
                ->orderBy('id')
                ->all();
        /* echo'<pre>';
          print_r($data);
          echo'</pre>';
          exit(); */
        return $this->render('outgoingview', [
                    'model' => $data,]);
    }

    /**
     * 
     * invoice view
     * 
     */

    /**
     * 
     * out view
     * 
     */
    public function actionOutView($id) {
        $model = InvoiceOutgoing::find()
                ->where(['id' => $id])
                ->one();
        return $this->render('view', ['model' => $model]);
    }

    public function actionIncomingInvoiceDelete($id) {
        $model = InvoiceIncoming::find()
                ->where(['id' => $id])
                ->one();
        $model->status = '2';
        $model->update(false);

        return $this->redirect(['incoming-invoice-view']);
    }

    public function actionOutgoingInvoiceDelete($id) {
        $model = InvoiceOutgoing::find()
                ->where(['id' => $id])
                ->one();
        $model->status = '2';
        $model->update(false);

        return $this->redirect(['outgoing-invoice-view']);
    }

    public function actionOutgoingInvoiceEdit($id) {
        $data = InvoiceOutgoing::find()
                ->where(['id' => $id])
                ->one();
        $data->update();
        if (Yii::$app->request->isPost) {
            $data->due_date = date('Y-m-d', strtotime($_POST['InvoiceOutgoing']['due_date']));
            $data->issue_date = date('Y-m-d', strtotime($_POST['InvoiceOutgoing']['issue_date']));
        }

views/invoice/index_incoming.php
<?php
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\base\View;
use yii\helpers\Url;
use yii\helpers\BaseUrl;

$this->title = 'Incoming Invoice List';
$this->params['breadcrumbs'][] = $this->title;
$this->registerCssFile('http://cdn.datatables.net/1.10.18/css/jquery.dataTables.min.css');
$this->registerJsFile('http://cdn.datatables.net/1.10.18/js/jquery.dataTables.min.js', ['depends' => 'yii\web\JqueryAsset']);
?>
<h1 class="page-title"> Incoming Invoice list
    <small>All incoming Invoices are listed here</small>
</h1>


<div class="content-wrapper">
    <section class="content">
        <div class="row">
            <div class="col-xs-12">

                <div class="box">
                    <div class="box-header">
                        <h1>Incoming Invoice Table</h1>
                        <a class="pull-right btn btn-primary" href="<?php echo Url::to(['invoice/incoming-invoice-create']); ?>"> Create Invoice</a>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">

                        <?php if (Yii::$app->session->hasFlash('excelFormSubmitted')) { ?>
                            <div class="alert alert-success"><button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">×</span>
                                </button> <?php echo Yii::$app->session->getFlash('excelFormSubmitted'); ?></div>
                        <?php } ?>
                        <div class="table-responsive" style="width: 100%">
                            <table class="table table-bordered table-striped" id='myTable'>
                                <thead>
                                    <tr>
                                        <th>issue_date</th>
                                        <th>due_date</th>
                                        <th>credit Time Line</th>
                                        <th>Payment Status</th>
                                        <th>Amount</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>


                                <tbody>

                                    <?php
                                    foreach ($model as $index => $value) {
                                        ?>
                                        <tr>
                                            <td><?php echo $value->issue_date ?></td>
                                            <td><?php echo $value->due_date ?></td>
                                            <td><?php
                                                $date = date("Y-m-d");
                                                $data = ($value->due_date);
                                                $d_start = new DateTime($date);
                                                $d_end = new DateTime($data);
                                                $diff = $d_start->diff($d_end);
                                                echo $diff->format("%R%a days");
                                                ?></td>
                                            <td><?php
                                                if ($value->payment_status == '1') {
                                                    echo '<span class="badge bg-green">Not Paid</span>';
                                                } else {
                                                    echo '<span class="badge bg-red"> Paid</span>';
                                                }
                                                ?>
                                            </td>
                                            <td>
                                                <?=$value->invoiceTotalAmount;?>
                                            </td>
                                            <td>
                                                <a href="<?php echo Yii::$app->request->baseurl . "/invoice/incoming-invoice-edit/" . $value->id ?>"><span class="badge bg-blue"><i class="fa fa-pencil"></i> Update</span></a>&nbsp;&nbsp;&nbsp;
                                                <a href="<?php echo Yii::$app->request->baseurl . "/invoice/incoming-invoice-delete/" . $value->id ?>"><span class="badge bg-red"><i class="fa fa-trash"></i>Delete </span></a>
                                                <a href="<?php echo Yii::$app->request->baseurl . "/invoice/incoming-invoice-view/" . $value->id ?>"><span class="badge bg-red"><i class="fa fa-eye"></i>View </span></a>
                                            </td>

                                        </tr>
                                        <?php
                                    }
                                    ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <!-- .box-body -->

                </div>

            </div>
        </div>
    </section>
</div>
<?php
$this->registerJs(
        '$(document).ready( function () {
    $("#myTable").DataTable();
} );'
);
?>

views/invoice/outgoingcreate.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\helpers\ArrayHelper;
use yii\grid\ActionColumn;
use app\models\Supplier;
use app\components\CustomPagination;
use richardfan\widget\JSRegister;

$this->title = 'Invoice Create';
$this->params['breadcrumbs'][] = $this->title;
?>
<h1><?= Html::encode($this->title) ?></h1>
<p>
    Create a correctly formatted Invoice.
</p>

<div class="row">
    <div class="col-lg-5">
        <?php $form = ActiveForm::begin(['id' => 'incoming', 'options' => ['enctype' => 'multipart/form-data', 'method' => 'post']]); ?>
         <?= $form->field($model, 'supplieir_id') ->dropDownList( ArrayHelper::map(Supplier::find()->asArray()->all(), 'supplier_id', 'name'),['prompt'=>'Choose...']) ?>
         <?= $form->field($model, 'name')->textInput(['type' => 'text', 'maxlength' => true, 'class' => 'form-control']) ?>
          <?= $form->field($model, 'destination')->textInput(['type' => 'text', 'maxlength' => true, 'class' => 'form-control']) ?>
        <?= $form->field($model, 'amount')->textInput(['type' => 'number', 'maxlength' => true, 'class' => 'form-control']) ?>
           <?= $form->field($model, 'startdate')->textInput(['maxlength' => true, 'class' => 'datepicker form-control']) ?>
 <?= $form->field($model, 'enddate')->textInput(['maxlength' => true, 'class' => 'datepicker form-control']) ?>

        <?= $form->field($model, 'issue_date')->textInput(['maxlength' => true, 'class' => 'datepicker form-control']) ?>

        <?= $form->field($model, 'due_date')->textInput(['maxlength' => true, 'class' => 'datepicker form-control']) ?>
         <?= $form->field($model, 'payment_status')->radioList(array('0' => 'Paid', '1' => 'Not Paid')); ?>
        <?= $form->field($model, 'file')->fileInput() ?>         
        <div class="form-group">
            <?= Html::submitButton('Submit', ['class' => 'btn btn-primary']) ?>
        </div>
        <?php ActiveForm::end(); ?>
    </div>
</div>
<?php JSRegister::begin(); ?>
<script>
    $(".datepicker").datepicker({
        format: "yy-mm-dd"
    });
</script>
<?php JSRegister::end(); ?>

views/invoice/outgoingview.php
<?php
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\base\View;
use yii\helpers\Url;
use yii\helpers\BaseUrl;

$this->title = 'Outgoing Invoice List';
$this->params['breadcrumbs'][] = $this->title;
$this->registerCssFile('http://cdn.datatables.net/1.10.18/css/jquery.dataTables.min.css');
$this->registerJsFile('http://cdn.datatables.net/1.10.18/js/jquery.dataTables.min.js', ['depends' => 'yii\web\JqueryAsset']);
?>
<h1 class="page-title"> Outgoing Invoice list
    <small>All Outgoing Invoices are listed here</small>
</h1>


<div class="content-wrapper">
    <section class="content">
        <div class="row">
            <div class="col-xs-12">

                <div class="box">
                    <div class="box-header">
                        <h1>Outgoing Invoice Table</h1>
                        <a class="pull-right btn btn-primary" href="<?php echo Url::to(['invoice/outgoing-invoice-create']); ?>"> Create Invoice</a>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">

                        <?php if (Yii::$app->session->hasFlash('excelFormSubmitted')) { ?>
                            <div class="alert alert-success"><button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">×</span>
                                </button> <?php echo Yii::$app->session->getFlash('excelFormSubmitted'); ?></div>
                        <?php } ?>
                        <div class="table-responsive" style="width: 100%">
                            <table class="table table-bordered table-striped" id='myTable'>
                                <thead>
                                    <tr>
                                        <th>supplier_id</th>
                                        <th>Name</th>
                                        <th>Destination</th>
                                        <th>start Date</th>
                                        <th>End Date</th>
                                        <th>amount</th>
                                        <th>issue_date</th>
                                        <th>due_date</th>
                                         <th>credit Time Line</th>
                                        <th>Payment Status</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>


                                <tbody>

                                    <?php
                                    foreach ($model as $index => $value) {
                                        ?>
                                        <tr>
                                            <td><?php echo $value->supplieir_id ?></td>
                                             <td><?php echo $value->name ?></td>
                                            <td><?php echo $value->destination ?></td>
                                            <td><?php echo $value->startdate ?></td>
                                            <td><?php echo $value->enddate ?></td>
                                            <td><?php echo $value->amount ?></td>
                                            <td><?php echo $value->issue_date ?></td>
                                            <td><?php echo $value->due_date ?></td>
<!--                                            <td><a class="badge bg-info" href="<?php echo Yii::$app->request->baseurl . "/uploads/invoice/outgoing/" . $value->upload_invoice ?>" download><?php echo $value->upload_invoice ?></a> </td>-->
                                           <td><?php
                                           $date=date("Y-m-d");
                                           $data=($value->due_date);
                                           $d_start = new DateTime($date);
                                            $d_end  = new DateTime($data); 
                                            $diff = $d_start->diff($d_end); 
                                           echo $diff->format("%R%a days");?></td>
                                            <td><?php
                                                if ($value->payment_status == '1') {
                                                    echo '<span class="badge bg-green">NotPaid</span>';
                                                } else {
                                                    echo '<span class="badge bg-red"> Paid</span>';
                                                }
                                                ?>
                                            </td>


                                            <td>
                                                <a href="<?php echo Yii::$app->request->baseurl . "/invoice/outgoing-invoice-edit?id=" . $value->id ?>"><span class="badge bg-blue"><i class="fa fa-trash"></i> Update</span></a>&nbsp;&nbsp;&nbsp;
                                                <a href="<?php echo Yii::$app->request->baseurl . "/invoice/outgoing-invoice-delete?id=" . $value->id ?>"><span class="badge bg-red"><i class="fa fa-pencil"></i>Delete </span></a>
                                               <a href="<?php echo Yii::$app->request->baseurl . "/invoice/out-view?id=" . $value->id ?>"><span class="badge bg-red"><i class="fa fa-eye"></i>View </span></a>
                                            </td>

                                        </tr>
                                        <?php
                                    }
                                    ?>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <!-- .box-body -->

                </div>

            </div>
        </div>
    </section>
</div>
<?php
$this->registerJs(
        '$(document).ready( function () {
    $("#myTable").DataTable();
} );'
);
?>

views/invoice/view_incoming.php
<style>
    .modal-full{
        width: 60%;
    }
    label{
        font-weight: 800 !important;
    }
    .form-control{
        border: 1px solid !important;
    }
    .compose-mail input, .compose-mail input:focus {
        border: none;
        padding: 0;
        width: 90%;
        float: left;
    }
    .ck-editor__editable {
        min-height: 165px;
    }

</style>

<?php

use yii\widgets\ActiveForm;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\helpers\BaseUrl;
use yii\grid\GridView;
use yii\grid\ActionColumn;
use app\models\Videos;

$this->title = 'Incoming Invoice Details';
?>
<div class="row">
    <div class="col-md-12">
        <h2 class="section-heading text-center">
            Incoming InVoice

        </h2>
    </div>
    <div class="col-md-12">
        <div class="head-text-container">
            <div class="sec-head left-sec-head">

                <div class="head-text col-md-3">
                    <b>Supplier</b> : <?= print_r($model->supplier->name); ?>
                </div>
                <div class="head-text col-md-3">
                    <b>Amount</b>  : <?= $model->invoiceTotalAmount; ?>
                </div>
                <div class="head-text col-md-3 ">
                    <b>Issue Date: </b>  <?= date('d/m/Y', strtotime($model->issue_date)); ?>
                </div>
                <div class="head-text col-md-3 ">
                    <b> Due Date: </b> <?= date('d/m/Y', strtotime($model->due_date)); ?>

                </div>

                <div class="head-text col-md-3">
                    <b> Payment: </b> <?php
                    if ($model->payment_status == '0') {
                        echo '<div class="badge bg-green">Paid</div>';
                    } else {
                        echo '<div class="badge bg-red"> Not Paid</div>';
                    }
                    ?>
                </div>
                <div class="head-text col-md-3">
                    <b>Currency: </b> <?php
                    if ($model->payment_status == '1') {
                        echo '<div class="badge bg-green">Thai Baht</div>';
                    } else {
                        echo '<div class="badge bg-green"> USD</div>';
                    }
                    ?>
                </div>
            </div>

        </div>
    </div>
    <div class="clearfix"></div>
    <div class="col-md-12">
        <table class="table table-bordered table-striped dataTable no-footer" id="ps_supplier_particulars">
            <thead>
                <tr>
                    <th colspan="100" class="text-center table-header">Particulars For this Invoice</th>
                </tr>
                <tr>
                    <th rowspan="2">Date Of service</th>
                    <th rowspan="2">Invoice No</th>
                    <th rowspan="2">Booking No</th>
                    <th rowspan="2">Tour Name</th>
                    <th rowspan="2">Guest Name</th>
                    <th colspan="2" class="text-center">PAX</th>
                    <th rowspan="2">Amount</th>
                </tr>
                <tr>
                    <th>Adult</th>
                    <th>Child</th>

                </tr>
            </thead>
            <tbody>
                <?php if (!empty($model->invoiceParticulars)) {
                    foreach ($model->invoiceParticulars as $index => $value) {
                        ?>
                <tr>
                <td><?= date('d/m/Y', strtotime($value->service_date)); ?></td>
                <td><?= $value->invoice_no; ?></td>
                <td><?= $value->booking_no; ?></td>
                <td><?= $value->tour_name; ?></td>
                <td><?= $value->guest_name; ?></td>
                <td><?= $value->adult_count; ?></td>
                <td><?= $value->child_count; ?></td>
                <td><?= $value->amount; ?></td>
                </tr>
                    <?php
                    }
                }else{
                ?>
                <tr>No data To Show </tr>
                <?php } ?>
            </tbody>
        </table>

    </div>
    <div class="col-md-12">
        <label>Uploaded File</label>
    <!--<iframe src="http://docs.google.com/viewer?url=http://soluciones.toshiba.com/media/downloads/products/4555c-5055cBrochure.pdf&embedded=true" width="600" height="780" style="border: none;"></iframe>-->
        <center><iframe src="http://docs.google.com/viewer?url=<?= Url::Base(true) . '/uploads/invoice/incoming/' . $model->upload_invoice; ?>&embedded=true" width="600" height="780" style="border: none;"></iframe></center>
    </div>