models/Flights.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "flights".
 *
 * @property string $id
 * @property string $flight_id
 * @property string $flight_date
 * @property string $source
 * @property string $destination
 * @property string $departure_time
 * @property string $arrival_time
 * @property string $created_at
 * @property string $updated_at
 * @property string $status
 */
class Flights extends \yii\db\ActiveRecord {

    /**
     * {@inheritdoc}
     */
    public static function tableName() {
        return 'flights';
    }

    /**
     * {@inheritdoc}
     */
    public function rules() {
        return [
            [['flight_date', 'created_at', 'updated_at','visa_on_arrival'], 'safe'],
            [['source', 'destination', 'flight_date', 'flight_id', 'status'], 'required', 'on' => 'create_voucher_manual'],
            [['status', 'visa_on_arrival'], 'string'],
            [['flight_id'], 'string', 'max' => 50],
            [['source', 'destination', 'departure_time', 'arrival_time'], 'string', 'max' => 20],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels() {
        return [
            'id' => 'ID',
            'flight_id' => 'Flight ID',
            'flight_date' => 'Flight Date',
            'source' => 'Source',
            'destination' => 'Destination',
            'departure_time' => 'Departure Time',
            'arrival_time' => 'Arrival Time',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'status' => 'Status',
        ];
    }

    public function getVoucher() {
        return $this->hasOne(Voucher::className(), ['id' => 'voucher_id']);
    }
}

controllers/ReportController.php
<?php

namespace app\controllers;

use Yii;
use app\components\CommonController;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use app\models\LoginForm;
use app\models\Transfers;
use \app\models\Activity;
use app\models\Flights;
use kartik\mpdf\Pdf;

class ReportController extends CommonController {

    /**
     * Index action.
     *
     * @return string
     */
    public function actionIndex() {
        return $this->render('index');
    }

    /**
     * opens the daily transfer Report
     * @return type
     */
    public function actionDailyTransferReport() {
        $upper = date('Y-m-d');
        $lower = date('Y-m-d');
        $city_name = 'BANGKOK';
        $city_key = 'BKK';
        if (Yii::$app->request->isPost) {
            $lower = isset($_POST['order-start-date']) && !empty($_POST['order-start-date']) ? date('Y-m-d', strtotime(explode(' - ', $_POST['order-start-date'])[0])) : '0000-00-00';
            $upper = isset($_POST['order-start-date']) && !empty($_POST['order-start-date']) ? date('Y-m-d', strtotime(explode(' - ', $_POST['order-start-date'])[1])) : '2090-12-31';
            $lower1 = isset($_POST['tour-start-date']) && !empty($_POST['tour-start-date']) ? date('Y-m-d', strtotime(explode(' - ', $_POST['tour-start-date'])[0])) : '0000-00-00';
            $upper1 = isset($_POST['tour-start-date']) && !empty($_POST['tour-start-date']) ? date('Y-m-d', strtotime(explode(' - ', $_POST['tour-start-date'])[1])) : '2090-12-31';
            $city = isset($_POST['city']) && !empty($_POST['city']) ? Yii::$app->request->post('city') : '';
            if ($city == 2) {
                $model = Transfers::find()->where(['<>', 'status', '2'])->andWhere(['and', "DATE(transfer_date)>='$lower1'", "DATE(transfer_date)<='$upper1'"])->andWhere(['and', "DATE(created_at)>='$lower'", "DATE(created_at)<='$upper'"])->andWhere(['or', "UPPER(transfer_source) LIKE '%PT%' OR UPPER(transfer_source) LIKE '%Pattaya%'", "UPPER(transfer_destination) LIKE '%BKK%' OR UPPER(transfer_destination) LIKE '%Bangkok%'"])->orderBy(['id' => SORT_DESC])->all();
            } else if ($city == 3) {
                $model = Transfers::find()->where(['<>', 'status', '2'])->andWhere(['and', "DATE(transfer_date)>='$lower1'", "DATE(transfer_date)<='$upper1'"])->andWhere(['and', "DATE(created_at)>='$lower'", "DATE(created_at)<='$upper'"])->andWhere(['or', "UPPER(transfer_source) LIKE '%HKT%' OR UPPER(transfer_source) LIKE '%PHUKET%'", "UPPER(transfer_destination) LIKE '%KBV%' OR UPPER(transfer_destination) LIKE '%KRABI%'"])->orderBy(['id' => SORT_DESC])->all();
            } else if ($city == 4) {
                $model = Transfers::find()->where(['<>', 'status', '2'])->andWhere(['and', "DATE(transfer_date)>='$lower1'", "DATE(transfer_date)<='$upper1'"])->andWhere(['and', "DATE(created_at)>='$lower'", "DATE(created_at)<='$upper'"])->andWhere(['or', "UPPER(transfer_source) LIKE '%KBV%' OR UPPER(transfer_source) LIKE '%KRABI%'", "UPPER(transfer_destination) LIKE '%HKT%' OR UPPER(transfer_destination) LIKE '%PHUKET%'"])->orderBy(['id' => SORT_DESC])->all();
            } else if ($city == 5) {
                $model = Transfers::find()->where(['<>', 'status', '2'])->andWhere(['and', "DATE(transfer_date)>='$lower1'", "DATE(transfer_date)<='$upper1'"])->andWhere(['and', "DATE(created_at)>='$lower'", "DATE(created_at)<='$upper'"])->andWhere(['or', "UPPER(transfer_source) LIKE '%BKK%' OR UPPER(transfer_source) LIKE '%Bangkok%' OR UPPER(transfer_destination) LIKE '%BKK%' OR UPPER(transfer_destination) LIKE '%Bangkok%'", "UPPER(transfer_source) LIKE '%PT%' OR UPPER(transfer_source) LIKE '%Pattaya%' OR UPPER(transfer_destination) LIKE '%PT%' OR UPPER(transfer_destination) LIKE '%Pattaya%'"])->orderBy(['id' => SORT_DESC])->all();
            } else if ($city == 6) {
                $model = Transfers::find()->where(['<>', 'status', '2'])->andWhere(['and', "DATE(transfer_date)>='$lower1'", "DATE(transfer_date)<='$upper1'"])->andWhere(['and', "DATE(created_at)>='$lower'", "DATE(created_at)<='$upper'"])->andWhere(['or', "UPPER(transfer_source) LIKE '%KBV%' OR UPPER(transfer_source) LIKE '%KRABI%' OR UPPER(transfer_destination) LIKE '%KBV%' OR UPPER(transfer_destination) LIKE '%KRABI%'", "UPPER(transfer_source) LIKE '%HKT%' OR UPPER(transfer_source) LIKE '%PHUKET%' OR UPPER(transfer_destination) LIKE '%HKT%' OR UPPER(transfer_destination) LIKE '%PHUKET%'"])->orderBy(['id' => SORT_DESC])->all();
            } else {
                $model = Transfers::find()->where(['<>', 'status', '2'])->andWhere(['and', "DATE(transfer_date)>='$lower1'", "DATE(transfer_date)<='$upper1'"])->andWhere(['and', "DATE(created_at)>='$lower'", "DATE(created_at)<='$upper'"])->orderBy(['id' => SORT_DESC])->all();
            }
            return $this->render('daily_transfer_report', ['model' => $model]);
        }
        $model = Transfers::find()->where(['<>', 'status', '2'])->andWhere(['and', "DATE(transfer_date)>='$lower'", "DATE(transfer_date)<='$upper'"])->orderBy(['id' => SORT_DESC])->all();

        return $this->render('daily_transfer_report', ['model' => $model]);
    }

    /**
     * opens the daily tour Report
     * @return type
     */
    public function actionDailyTourReport() {
        $upper = date('Y-m-d');
        $lower = date('Y-m-d');
        if (Yii::$app->request->isPost) {
            $lower = isset($_POST['order-start-date']) && !empty($_POST['order-start-date']) ? date('Y-m-d', strtotime(explode(' - ', $_POST['order-start-date'])[0])) : '0000-00-00';
            $upper = isset($_POST['order-start-date']) && !empty($_POST['order-start-date']) ? date('Y-m-d', strtotime(explode(' - ', $_POST['order-start-date'])[1])) : '2090-12-31';
            $lower1 = isset($_POST['tour-start-date']) && !empty($_POST['tour-start-date']) ? date('Y-m-d', strtotime(explode(' - ', $_POST['tour-start-date'])[0])) : '0000-00-00';
            $upper1 = isset($_POST['tour-start-date']) && !empty($_POST['tour-start-date']) ? date('Y-m-d', strtotime(explode(' - ', $_POST['tour-start-date'])[1])) : '2090-12-31';
            $city = isset($_POST['city']) && !empty($_POST['city']) ? Yii::$app->request->post('city') : '';
            $model = Activity::find()->where(['<>', 'status', '2'])->andWhere(['and', "tour_date>=DATE('$lower1')", "tour_date<=DATE('$upper1')"])->andWhere(['and', "DATE(created_at)>='$lower'", "DATE(created_at)<='$upper'"])->orderBy(['tour_date' => SORT_DESC, 'UPPER(tour_name)' => SORT_DESC])->andWhere(['LIKE', 'destination', $city])->all();
            return $this->render('daily_tour_report', ['model' => $model]);
        }
        $model = Activity::find()->where(['<>', 'status', '2'])->andWhere(['and', "tour_date>='$lower'", "tour_date<='$upper'"])->orderBy(['id' => SORT_DESC])->all();

        return $this->render('daily_tour_report', ['model' => $model]);
    }

    /**
     * lets you force download a pdf file for the transfers filtered by date
     * @return type
     */
    function actionDownloadTransferPdf() {

        $upper = date('Y-m-d');
        $lower = date('Y-m-d');
        if (Yii::$app->request->isPost) {

            $lower = isset($_POST['order-start-date']) && !empty($_POST['order-start-date']) ? date('Y-m-d', strtotime(explode(' - ', $_POST['order-start-date'])[0])) : '0000-00-00';
            $upper = isset($_POST['order-start-date']) && !empty($_POST['order-start-date']) ? date('Y-m-d', strtotime(explode(' - ', $_POST['order-start-date'])[1])) : '2090-12-31';
            $lower1 = isset($_POST['tour-start-date']) && !empty($_POST['tour-start-date']) ? date('Y-m-d', strtotime(explode(' - ', $_POST['tour-start-date'])[0])) : '0000-00-00';
            $upper1 = isset($_POST['tour-start-date']) && !empty($_POST['tour-start-date']) ? date('Y-m-d', strtotime(explode(' - ', $_POST['tour-start-date'])[1])) : '2090-12-31';


            if (isset($_POST['order-start-date']) && !empty($_POST['order-start-date'])) {
                $date = date('l jS \of F Y', strtotime(explode(' - ', $_POST['order-start-date'])[0]));
                $date .= ' to ' . date('l jS \of F Y', strtotime(explode(' - ', $_POST['order-start-date'])[1]));
            } else if (isset($_POST['tour-start-date']) && !empty($_POST['tour-start-date'])) {
                $date = date('l jS \of F Y', strtotime(explode(' - ', $_POST['tour-start-date'])[0]));
                $date .= ' to ' . date('l jS \of F Y', strtotime(explode(' - ', $_POST['tour-start-date'])[1]));
            } else {
                $date = date('l jS \of F Y', strtotime(explode(' - ', $lower)));
                $date = date('l jS \of F Y', strtotime(explode(' - ', $upper)));
            }
            $model = Transfers::find()->where(['<>', 'status', '2'])->andWhere(['and', "DATE(transfer_date)>='$lower1'", "DATE(transfer_date)<='$upper1'"])->andWhere(['and', "DATE(created_at)>='$lower'", "DATE(created_at)<='$upper'"])->orderBy(['id' => SORT_DESC])->all();
        } else {
            return $this->redirect(['daily-transfer-report']);
        }
        $this->layout = 'template';
//        return $this->render('../templates/mpdf_transfer_report');
        $content = $this->renderPartial('../templates/mpdf_transfer_report', ['model' => $model, 'date' => $date]);
        $pdf = new Pdf([
            'mode' => Pdf::MODE_UTF8,
            'filename' => 'Transfer Report.pdf',
            'format' => Pdf::FORMAT_A4,
            'orientation' => Pdf::ORIENT_PORTRAIT,
            'destination' => Pdf::DEST_DOWNLOAD,
            'content' => $content,
            'cssFile' => '@vendor/kartik-v/yii2-mpdf/assets/kv-mpdf-bootstrap.min.css',
            'cssInline' => '.img-container img {width: 100%;overflow: hidden;}',
            'options' => ['title' => 'Transfer Report'],
            'methods' => [
                'SetHeader' => ['Erawan'],
                'SetFooter' => ['{PAGENO}'],
            ]
        ]);
        $pdf->render();
    }

    /**

views/report/daily_tour_report.php
<style>
    .date-pick {
        width: 40%;
        display: inline-block;
    }
    .page-title-conntainer {
        margin: 1rem auto;
    }
    span.page-title {
        font-size: 3rem;
        line-height: 5rem;
        padding: 10px 10px;
        font-weight: 600;
        text-transform: capitalize;
    }
    span.page-title-2 {
        font-size: 1.6rem;
        line-height: 2rem;
        padding: 10px 10px;
        font-weight: 300;
        text-transform: capitalize;
    }
</style>

<?php

use yii\widgets\ActiveForm;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\grid\ActionColumn;
use app\models\Videos;
use app\components\CustomPagination;
use richardfan\widget\JSRegister;

$this->title = 'Daily Tour List';
$this->params['breadcrumbs'][] = $this->title;

$this->registerCssFile('https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css');
$this->registerCssFile('http://cdn.datatables.net/1.10.18/css/jquery.dataTables.min.css');
$this->registerJsFile('https://cdn.jsdelivr.net/momentjs/latest/moment.min.js', ['depends' => 'yii\web\JqueryAsset']);
$this->registerJsFile('https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js', ['depends' => 'yii\web\JqueryAsset']);
$this->registerJsFile('http://cdn.datatables.net/1.10.18/js/jquery.dataTables.min.js', ['depends' => 'yii\web\JqueryAsset']);
?>
<div class="transfer-filter">
    <div class="col-md-12 page-title-conntainer">
        <span class="page-title"> Daily Tour list</span>
        <span class="page-title-2">Day Wise Tours are listed here</span>
    </div>
    <div>
        <button class="btn btn-primary" type="button" id="ps_download_pdf">Download PDF</button>   
    </div>
    <?php $form = ActiveForm::begin(['id' => 'transfer-filter-form', 'options' => ['method' => 'post']]) ?>

    <div class="col-md-6">
        <div class="date-container form-group clearfix">
            <div class="col-md-2 text-right"> Order date </div>
            <div class="col-md-10"> 
                <input type="text" name="order-start-date" class="form-control" id="startDate-1" value="<?= $_POST['order-start-date'] ?? ''; ?>">
            </div> 
        </div>    
    </div>    
    <div class="col-md-6">
        <div class="date-container form-group clearfix">
            <div class="col-md-2 text-right">Transfer Date  </div>
            <div class="col-md-10">
                <input type="text" name="tour-start-date" class="form-control" id="startDate-2" value="<?= $_POST['tour-start-date'] ?? ''; ?>">
            </div>
        </div> 
    </div> 
    <div class="col-md-6">
        <div class="date-container form-group clearfix">
            <div class="col-md-2 text-right">City</div>
            <div class="col-md-10">
                <select name="city" class="form-control" id="ps_filter_report_tour">
                    <option value="">All City</option>
                    <option value="phuket" <?= isset($_POST['city']) && $_POST['city'] == 'phuket' ? 'selected' : '' ?>>Phuket</option>
                    <option value="krabi" <?= isset($_POST['city']) && $_POST['city'] == 'krabi' ? 'selected' : '' ?>>Krabi</option>
                    <option value="pattaya" <?= isset($_POST['city']) && $_POST['city'] == 'pattaya' ? 'selected' : '' ?>>Pattaya</option>
                    <option value="bangkok" <?= isset($_POST['city']) && $_POST['city'] == 'bangkok' ? 'selected' : '' ?>>Bangkok</option>
                    <option value="chiangmai" <?= isset($_POST['city']) && $_POST['city'] == 'chiangmai' ? 'selected' : '' ?>>Chiangmai</option>
                    <option value="samui" <?= isset($_POST['city']) && $_POST['city'] == 'samui' ? 'selected' : '' ?>>Samui</option>
                </select>
            </div>
        </div> 
    </div> 
    <div class="col-md-6 col-md-offset-3">
        <button class="btn btn-default" type="submit">Submit</button>
    </div>
</div> 
<?php ActiveForm::end(); ?>



</div>
<div class="table-responsive" style="width: 100%">
    <table class="table table-bordered table-striped table-condensed" id="myTable">
        <thead>
            <tr>
                <th colspan="14" class="text-center table-header">TOUR ITINERARY</th>
            </tr>
            <tr>
                <th>Customer Name</th>
                <th class="numeric">Adult</th>
                <th class="numeric">Child</th>
                <th class="numeric">Infant</th>
                <th>pickup Time</th>
                <th class="numeric">Meeting Point</th>
                <th class="numeric">Destination</th>
                <th class="numeric">Tour name</th>
                <th>Order Date</th>
                <th>Tour Date</th>
                <th class="numeric">Tour Type</th>
                <th class="numeric">Booking ID</th>
                <th class="numeric">Status</th>
                <th class="numeric">View</th>
            </tr>
        </thead>
        <tbody>
            <?php
            $flag = "info";
            $flag1 = FALSE;
            if (count($model) > 0) {
                foreach ($model as $index => $val) {
                    if ($flag1 == TRUE) {
                        ?>
                        <tr class="<?= $flag; ?>">
                            <?php
                            if (isset($model[$index + 1]) && strtoupper($model[$index + 1]->tour_date) == strtoupper($val->tour_date) && strpos(preg_replace('/\s+/u', '', strtoupper($model[$index + 1]->tour_name)), preg_replace('/\s+/u', '', strtoupper($val->tour_name)))) {

                                $flag1 = TRUE;
                            } else {
                                $flag = $flag == "info" ? "warning" : "info";
                                $flag1 = FALSE;
                            }
                        } else if (isset($model[$index + 1]) && strtoupper($model[$index + 1]->tour_date) == strtoupper($val->tour_date) && strpos(preg_replace('/\s+/u', '', strtoupper($model[$index + 1]->tour_name)), preg_replace('/\s+/u', '', strtoupper($val->tour_name)))) {
                            ?>
                        <tr class="<?= $flag; ?>">
                            <?php
                            $flag1 = TRUE;
                        } else {
                            $flag1 = FALSE;
                            ?>
                        <tr>
                        <?php }
                        ?>

                        <td><?= $val->voucher->billing_name; ?></td>
                        <td class="numeric"><?= $val->voucher->adult_count; ?></td>
                        <td class="numeric"><?= $val->voucher->child_count; ?></td>
                        <td class="numeric"><?= $val->voucher->infant_count; ?></td>
                        <td><?= !empty($val->pickup_time) ? $val->pickup_time : 'NA'; ?></td>
                        <td class="numeric"><?= $val->meeting_point; ?></td>
                        <td class="numeric"><?= $val->destination; ?></td>
                        <td class="numeric"><?= $val->tour_name; ?></td>
                        <td><?= date('d/m/Y', strtotime($val->created_at)); ?></td>
                        <td><?= date('d/m/Y', strtotime($val->tour_date)); ?></td>
                        <td class="numeric"><?= $val->tour_type; ?></td>
                        <td class="numeric"><?= '#' . $val->voucher->id; ?></td>
                        <td class="numeric"><?php
                            if ($val->status == '1') {
                                echo '<span class="badge bg-green">Active</span>';
                            } else {
                                echo '<span class="badge bg-red">Inactive</span>';
                            }
                            ?></td>
                        <td>
                            <a href="<?= Yii::$app->request->baseUrl . '/voucher/view/' . $val->voucher->id; ?> "><span class="badge bg-yellow"><i class="fa fa-eye"></i> View</span></a>&nbsp;&nbsp;&nbsp;</td>

                    </tr>
                    <?php
                }
            }
            ?>
            </tr>
        </tbody>
    </table>
</div>
<?php JSRegister::begin(); ?>
<script>
    $(document).ready(function () {
        $("#myTable").DataTable();
        $("#startDate-1").val('');
//        $("#myTable1").DataTable();
    });

    $("#ps_download_pdf").on('click', function () {

        $(document).ready(function () {
            $('<form action="<?php echo Url::to(['download-tour-pdf']); ?>" id="pdf-transfer-filter-form" method="post"></form>').appendTo('body');
            $("#transfer-filter-form").find(":input").clone().appendTo("#pdf-transfer-filter-form");
            $("#pdf-transfer-filter-form").submit();
        });
    });
    $('#startDate-1').daterangepicker({
        format: 'M/DD hh:mm A',
        ranges: {
            'Today': [moment(), moment()],
            'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
            'Tomorrow': [moment().add(1, 'days'), moment().add(1, 'days')],
            'Last 7 Days': [moment().subtract(6, 'days'), moment()],
            'Last 30 Days': [moment().subtract(29, 'days'), moment()],
            'This Month': [moment().startOf('month'), moment().endOf('month')],
            'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
        },
        "alwaysShowCalendars": true,
        "cancelClass": "btn-danger"

    });
    $('#startDate-1').on('cancel.daterangepicker', function (ev, picker) {
        $(this).val('');
    });
    $('#startDate-2').on('cancel.daterangepicker', function (ev, picker) {
        $(this).val('');
    });
    $('#startDate-2').daterangepicker({
        format: 'M/DD hh:mm A',
        ranges: {
            'Today': [moment(), moment()],
            'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
            'Tomorrow': [moment().add(1, 'days'), moment().add(1, 'days')],
            'Last 7 Days': [moment().subtract(6, 'days'), moment()],
            'Last 30 Days': [moment().subtract(29, 'days'), moment()],
            'This Month': [moment().startOf('month'), moment().endOf('month')],
            'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
        },
        "alwaysShowCalendars": true,
        "cancelClass": "btn-danger"

    });
</script>
<?php JSRegister::end(); ?>