models/Supplier.php
<?php

namespace app\models;

use Yii;


/**
 * This is the model class for table "supplier".
 *
 * @property string $id
 * @property string $supplier_id
 * @property string $name
 * @property string $email
 * @property string $phno
 * @property string $created_at
 * @property string $upadated_at
 * @property string $status
 */
class Supplier extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'supplier';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [[ 'supplier_id', 'name', 'email', 'phno','city'], 'required','on' => 'create'],
            [[ 'supplier_id', 'name', 'email', 'phno','city'], 'required','on' => 'update'],
            [['id'], 'integer'],
            [['created_at', 'upadated_at','city'], 'safe'],
            [['status'], 'string'],
            
            [['supplier_id', 'phno'], 'string', 'max' => 20],
            [['name', 'email'], 'string', 'max' => 255],
            [['id'], 'unique'],
           
             [['email'], 'email'],
             ['phno', 'integer'],
             ['phno', 'string', 'min'=>8],
            
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'supplier_id' => 'Supplier ID',
            'name' => 'Name',
            'email' => 'Email',
            'phno' => 'Phno',
            
            'city'=>'City',
            'created_at' => 'Created At',
            'upadated_at' => 'Upadated At',
            'status' => 'Status',
        ];
    }
    public function getSuppliertour() {
        return $this->hasMany(SupplierTourName::className(), ['supplier_id' => 'id']);
    }
}

controllers/SupplierController.php
<?php

namespace app\controllers;

use yii;
use app\components\CommonController;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use app\models\Transfers;
use app\models\Voucher;
use app\models\Flights;
use app\models\Activity;
use app\models\Car;
use app\models\Email;
use app\models\Supplier;
use app\models\SupplierTourName;
use yii\helpers\BaseFileHelper;
use yii\web\UploadedFile;
use yii\helpers\Url;

/**
 * Default controller for the `admin` module
 */
class SupplierController extends CommonController {

    /**
     * opens the List of all the not deleted vouchers in the system
     * @return string
     * For update of Supplier
     */
    public function actionIndex() {
        $model = Supplier::find()->where(['<>', 'status', '2'])->orderBy(['id' => SORT_DESC])->all();

        return $this->render('index', ['model' => $model]);
    }

    /**
     * 
     * @param type $id
     * @return type For Create of supplier 
     */
    public function actionCreate() {
        $supply = new Supplier(['scenario' => 'create']);
        $supplytour = new SupplierTourName(['scenario' => 'create']);
        if (Yii::$app->request->isPost) {
            $supply->attributes = $_POST['Supplier'];
            $supply->created_at = date('Y-m-d H:i:s');
            $supply->status = '1';
            if ($supply->save()) {
                if (isset($_POST['SupplierTourName'])) {
                    foreach ($_POST['SupplierTourName'] as $valueSupplierTourName) {
                        $supplytour = new SupplierTourName();
                        $supplytour->attributes = $valueSupplierTourName;
                        $supplytour->supplier_id = $supply->id;
                        $supplytour->save();
                    }

                    Yii::$app->session->setFlash('Suppliercreate', 'SupplierSubmitted');
                    return $this->redirect(['index']);
                }
            }
        }
        return $this->render('create', ['model' => $supply, 'model1' => $supplytour]);
    }

    /**
     * 
     * @param type $id
     * @return type For Edit of supplier 
     */
    public function actionEdit($id) {
        $data = Supplier::find()
                ->where(['id' => $id])
                ->one();
        $tour = SupplierTourName::find()
                ->where(['supplier_id' => $id])
                ->one();
        if (Yii::$app->request->isPost) {
// $data->scenario = 'update_supplier';
            $data->load(Yii::$app->request->post());
            $data->updated_at = date('Y-m-d H:i:s');
            if ($data->save()) {
                foreach ($data->suppliertour as $index => $value) {
                    $value->delete();
                }
                foreach ($_POST['SupplierTourName'] as $valueSupplierTourName) {
                    $supplytour = new SupplierTourName();
                    $supplytour->attributes = $valueSupplierTourName;
                    $supplytour->supplier_id = $data->id;
                    $supplytour->save();
                }
                Yii::$app->getSession()->setFlash('Suppliercreate', 'updated sucessfully');
                return $this->redirect(['index']);
            }
        }
        return $this->render('edit', [
                    'model' => $data, 'model1' => $tour]);
    }

    /**
     * 
     * @param type $id
     * @return type For view of supplier 
     */
    public function actionView($id) {
        $model = Supplier::find()
                ->where(['id' => $id])
                ->one();
        return $this->render('view', ['model' => $model]);
    }

    /**
     * 
     * @param type $id
     * @delete for supplier
     */
    public function actionDelete($id) {
        $model = Supplier::find()
                ->where(['id' => $id])
                ->one();
        if ($model->delete()) {
            
        }
        return $this->redirect(Url::to(['index']));
    }

    /**
     * add view as per need in the add voucher section form
     */
    public function actionAjaxTourAdd() {

        if (Yii::$app->request->isAjax) {
            $counter = $_POST['counter'] ?? '';
            echo $this->renderPartial('add_tours_ajax', ['counter' => $counter]);
            exit();
        } else {
            $response = [
                'status' => 'FAILED',
                'code' => '-99'
            ];
        }
        echo json_encode($response);

        exit();
    }

}

views/supplier/add_tours_ajax.php
<td>
    <input type="text" name="SupplierTourName[<?= $counter; ?>][tourname]" class="form-control" />
</td>
<td>
    <input type="text" name="SupplierTourName[<?= $counter; ?>][sic_adult_price]" class="form-control"/>
</td>
<td>
    <input type="text" name="SupplierTourName[<?= $counter; ?>][sic_child_price]" class="form-control"/>
</td>
<td>
    <input type="text" name="SupplierTourName[<?= $counter; ?>][ticket_adult_price]" class="form-control"/>
</td>
<td>
    <input type="text" name="SupplierTourName[<?= $counter; ?>][ticket_child_price]" class="form-control"/>
</td>
<td>
    <div class="">
        <button type="button" class="remove-flight btn btn-danger">Remove</button>
    </div>
</td>

views/supplier/create.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\grid\ActionColumn;
use app\components\CustomPagination;
use richardfan\widget\JSRegister;

$this->title = 'Supplier';
//$this->params['breadcrumbs'][] = $this->title;
/* @var $this yii\web\View */
/* @var $model app\models\InvoiceIncoming */
/* @var $form ActiveForm */
?>
<div class="supplier-create">
    <?php $form = ActiveForm::begin(['id' => 'supplier', 'options' => ['method' => 'post']]); ?>
    <div class="col-md-12">

        <div class="col-md-2">   <?= $form->field($model, 'supplier_id')->textInput(['autofocus' => true]) ?></div>

        <div class="col-md-2">         <?= $form->field($model, 'name') ?> </div>


        <div class="col-md-2">  <?= $form->field($model, 'email') ?> </div>

        <div class="col-md-2">      <?= $form->field($model, 'phno') ?> </div>

        <?php $city = ['BKK' => 'BANGKOK', 'PT' => 'PATTAYA', 'HKT' => 'PHUKET', 'KBV' => 'KRABI', 'USM' => 'SAMUI', 'CNX' => 'CHIANGMAI']; ?>
        <div class="col-md-2">  <?= $form->field($model, 'city')->dropDownList($city, ['prompt' => 'Select Option']); ?> </div>
    </div>
    <div class="col-md-12">
        <table id="ps_tour_table" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th rowspan="2">
                        Tour Name
                    </th>
                    <th colspan="2" class="text-center">SIC PRICE</th>
                    <th colspan="2" class="text-center">Ticket PRICE</th>
                    <th rowspan="2">
                        <button type="button" id="" class="add-item btn btn-primary">Add More</button>
                    </th>
                </tr>
                <tr>
                    <th >Adult</th>
                    <th >Child</th>
                    <th >Adult</th>
                    <th >Child</th>

                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        <input type="text" name="SupplierTourName[0][tourname]" class="form-control"/>
                    </td>
                    <td>
                        <input type="text" name="SupplierTourName[0][sic_adult_price]" class="form-control"/>
                    </td>
                    <td>
                        <input type="text" name="SupplierTourName[0][sic_child_price]" class="form-control"/>
                    </td>
                    <td>
                        <input type="text" name="SupplierTourName[0][ticket_adult_price]" class="form-control"/>
                    </td>
                    <td>
                        <input type="text" name="SupplierTourName[0][ticket_child_price]" class="form-control"/>
                    </td>
                    <td>
                        <button  type="button" id="" class="btn btn-danger">Remove</button>
                    </td>
                </tr>
            </tbody>
        </table>
        <div class="form-group" style="padding-top:23px">
            <?= Html::submitButton('Submit', ['class' => 'btn btn-primary']) ?>
        </div>
        <?php ActiveForm::end(); ?>
    </div>
</div><!-- invoice-create -->
<?php JSRegister::begin(); ?>
<script>
    $(document).ready(function () {
        $("#ps_tour_table").on("click", ".btn.btn-danger", function (event) {
            $(this).closest("tr").remove();
        });
        var tour_counter = 1;
        $(".add-item").on('click', function () {
            $.ajax({
                type: "POST",
                evalScripts: true,
                url: '<?= Url::to('ajax-tour-add'); ?>',
                data: ({_csrf: yii.getCsrfToken(), counter: tour_counter}),
                success: function (data) {
                    $("#ps_tour_table").find('tbody:last').append('<tr>').find('tr:last').append(data);
                    tour_counter++;
                }
            });
        });
    });
</script>
<?php JSRegister::end(); ?>

views/supplier/edit.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use yii\helpers\BaseUrl;
use yii\grid\GridView;
use yii\grid\ActionColumn;
use app\components\CustomPagination;
use richardfan\widget\JSRegister;

$this->title = 'Supplier';
//$this->params['breadcrumbs'][] = $this->title;
/* @var $this yii\web\View */
/* @var $model app\models\InvoiceIncoming */
/* @var $form ActiveForm */
?>
<?php $form = ActiveForm::begin(['id' => 'supplier', 'options' => ['method' => 'post']]); ?>
<div class="supplier-create">
    <div class="col-md-12">

        <div class="col-md-2">   <?= $form->field($model, 'supplier_id')->textInput(['autofocus' => true]) ?></div>

        <div class="col-md-2">         <?= $form->field($model, 'name') ?> </div>


        <div class="col-md-2">  <?= $form->field($model, 'email') ?> </div>

        <div class="col-md-2">      <?= $form->field($model, 'phno') ?> </div>

        <?php $city = ['BKK' => 'BANGKOK', 'PT' => 'PATTAYA', 'HKT' => 'PHUKET', 'KBV' => 'KRABI', 'USM' => 'SAMUI', 'CNX' => 'CHIANGMAI']; ?>
        <div class="col-md-2">  <?= $form->field($model, 'city')->dropDownList($city, ['prompt' => 'Select Option']); ?> </div>
    </div>
    <div class="col-md-12">
        <table id="ps_tour_table" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th rowspan="2">
                        Tour Name
                    </th>
                    <th colspan="2" class="text-center">SIC PRICE</th>
                    <th colspan="2" class="text-center">Ticket PRICE</th>
                    <th rowspan="2">
                        <button type="button" id="" class="add-item btn btn-primary">Add More</button>
                    </th>
                </tr>
                <tr>
                    <th >Adult</th>
                    <th >Child</th>
                    <th >Adult</th>
                    <th >Child</th>

                </tr>
            </thead>
            <tbody>
                <?php
                if (isset($model->suppliertour) && !empty($model->suppliertour)) {
                    foreach ($model->suppliertour as $index1 => $value1) {
                        ?>
                        <tr>
                            <td>
                                <input type="text" name="SupplierTourName[<?= $index1; ?>][tourname]" class="form-control" value="<?= $value1->tourname; ?>"/>
                            </td>
                            <td>
                                <input type="text" name="SupplierTourName[<?= $index1; ?>][sic_adult_price]" class="form-control" value="<?= $value1->sic_adult_price; ?>"/>
                            </td>
                            <td>
                                <input type="text" name="SupplierTourName[<?= $index1; ?>][sic_child_price]" class="form-control" value="<?= $value1->sic_child_price; ?>"/>
                            </td>
                            <td>
                                <input type="text" name="SupplierTourName[<?= $index1; ?>][ticket_adult_price]" class="form-control" value="<?= $value1->ticket_adult_price; ?>"/>
                            </td>
                            <td>
                                <input type="text" name="SupplierTourName[<?= $index1; ?>][ticket_child_price]" class="form-control" value="<?= $value1->ticket_child_price; ?>"/>
                            </td>
                            <td>
                                <button  type="button" id="" class="btn btn-danger">Remove</button>
                            </td>
                        </tr>
                        <?php
                    }
                }
                ?>



            </tbody>
        </table>
        <div class="form-group" style="padding-top:23px">
            <?= Html::submitButton('Submit', ['class' => 'btn btn-primary']) ?>
        </div>
        <?php ActiveForm::end(); ?>
    </div>
</div><!-- invoice-create -->
<?php JSRegister::begin(); ?>
<script>
    $(document).ready(function () {
        $("#ps_tour_table").on("click", ".btn.btn-danger", function (event) {
            $(this).closest("tr").remove();
        });
        var tour_counter = 1;
        $(".add-item").on('click', function () {
            $.ajax({
                type: "POST",
                evalScripts: true,
                url: '<?= Url::to(Baseurl::base() . '/supplier/ajax-tour-add'); ?>',
                data: ({_csrf: yii.getCsrfToken(), counter: tour_counter}),
                success: function (data) {
                    $("#ps_tour_table").find('tbody:last').append('<tr>').find('tr:last').append(data);
                    tour_counter++;
                }
            });
        });
    });
</script>
<?php JSRegister::end(); ?>

views/supplier/index.php
<?php

use yii\widgets\ActiveForm;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\grid\ActionColumn;
use richardfan\widget\JSRegister;
use app\components\CustomPagination;

$this->registerCssFile('http://cdn.datatables.net/1.10.18/css/jquery.dataTables.min.css');
$this->registerJsFile('http://cdn.datatables.net/1.10.18/js/jquery.dataTables.min.js', ['depends' => 'yii\web\JqueryAsset']);
$this->title = 'Supplier List';
$this->params['breadcrumbs'][] = $this->title;
?>

<h1 class="page-title"> Supplier List
    <small>All Supplier are listed here</small>
</h1>


<div class="content-wrapper">
    <section class="content">
        <div class="row">
            <div class="col-xs-12">

                <div class="box">
                    <div class="box-header">
                        <h1>Supplier Table</h1>
                        <a class="pull-right btn btn-primary" href="<?php echo Url::to(['supplier/create']); ?>"> create Supplier</a>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">

                        <?php if (Yii::$app->session->hasFlash('Suppliercreate')) { ?>
                            <div class="alert alert-success"><button type="button" class="close" data-dismiss="alert" aria-label="Close">

                                </button> <?php echo Yii::$app->session->getFlash('Suppliercreate'); ?></div>
                        <?php } ?>
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th> SupplierId</th>
                                    <th>Email</th>
                                    <th>PhNo</th>


                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                if (isset($model) && !empty($model)):
                                    foreach ($model as $val) {
                                        ?>
                                        <tr>
                                            <td><?php echo $val->supplier_id; ?></td>
                                            <td><?php echo $val->email; ?></td>
                                            <td><?php echo $val->phno; ?></td>

                                            <td>
                                                <a href="<?= Yii::$app->request->baseUrl . '/supplier/view/' . $val->id; ?> "><span class="badge bg-yellow"><i class="fa fa-eye"></i> View</span></a>&nbsp;&nbsp;&nbsp;
                                                <a href="<?= Yii::$app->request->baseUrl . '/supplier/edit/' . $val->id; ?> "><span class="badge bg-yellow"><i class="fa fa-pencil"></i> Edit</span></a>&nbsp;&nbsp;&nbsp;
                                                <a href="<?= Yii::$app->request->baseUrl . '/supplier/delete/' . $val->id; ?> "><span class="badge bg-red"><i class="fa fa-trash"></i> Delete</span></a>&nbsp;&nbsp;&nbsp;
                                            </td>
                                        </tr>
                                        <?php
                                    }
                                endif;
                                ?>
                            </tbody>
                        </table>
                    </div>
                    <!-- .box-body -->

                </div>

            </div>
        </div>
    </section>
</div>
<?php JSRegister::begin(); ?>
<script>
    $(document).ready(function () {
        $("#example1").DataTable();
        //        $("#myTable1").DataTable();
    });
</script>
<?php JSRegister::end(); ?>

views/supplier/view.php
<div class="row">
    <div class="col-md-12">
        <h2 class="section-heading text-center">
            Supplier  For : <?= $model->supplier_id; ?>
        </h2>
    </div>

    <div class="col-md-12">
        <div class="head-text-container">
            <span class="head-text">
                <label> Name</label> : <?= $model->name; ?>
            </span>
        </div>
    </div>

    <div class="col-md-12">
        <div class="head-text-container">

            <span class="head-text">
                <label>   Email </label>: <?= $model->email; ?>
            </span>
        </div>
    </div>
    <div class="col-md-12">
        <div class="head-text-container">

            <span class="head-text">
                <label>   PhNo </label>: <?= $model->phno; ?>
            </span>
        </div>
    </div>
    <div class="col-md-12">
        <div class="head-text-container">

            <span class="head-text">
                <label>   City </label>: <?= $model->city; ?>
            </span>
        </div>
    </div>
    <div class="col-md-12">
        <div class="head-text-container">
            <span>
                <table id="ps_tour_table" class="table table-bordered table-striped">
            <thead>
                <tr>
                     <th rowspan="2">
                        Tour Name
                    </th>
                    <th colspan="2" class="text-center">SIC PRICE</th>
                    <th colspan="2" class="text-center">Ticket PRICE</th>
                    
                </tr>
                <tr>
                    <th >Adult</th>
                    <th >Child</th>
                    <th >Adult</th>
                    <th >Child</th>

                </tr>
            </thead>
            <tbody>
                 <?php
                $var = '';
                if (isset($model->suppliertour) && !empty($model->suppliertour)) {
                    foreach ($model->suppliertour as $index1 => $value1) { ?>
                        
                <tr> <td ><?=$value1->tourname ; ?></td>
               <td><?= $value1->sic_adult_price; ?></td>
                     <td><?= $value1->sic_child_price; ?></td>
                    <td><?= $value1->ticket_adult_price; ?></td>
                     <td><?= $value1->ticket_child_price; ?></td>
                <?php      
                   
                 }
                  
                } else {
                     'No tour name added yet.';
                }
              ?>
            
                </tr>
            </tbody>
             </table>
            </span>
        </div>
    </div>
</div>